-dontwarn com.intellij.openapi.diagnostic.Logger
-dontwarn com.intellij.openapi.util.Key
-dontwarn javax.annotation.processing.AbstractProcessor
-dontwarn org.fusesource.jansi.Ansi
-dontwarn org.jetbrains.annotations.NonNls
-dontwarn org.jetbrains.annotations.NotNull
-dontwarn org.jetbrains.annotations.Nullable